# Generated by Django 3.1 on 2020-08-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='data_match',
            new_name='date_match',
        ),
    ]
